#!/bin/csh
cd ./
setenv CURRIT 1
setenv RUN ./
setenv NEWIT $RUN/structures/it1
setenv PREVIT $RUN/structures/it1
setenv TEMPTRASH $RUN
if ( `ls -1 $NEWIT/analysis/*fit_*.pdb | wc -l` > 1) then
  protocols/cns1 < protocols/rmsd.inp >! $NEWIT/analysis/rmsd.out
  gzip -f $NEWIT/analysis/rmsd.out
else
  echo "Cluster 1 -> 1" >$NEWIT/analysis/cluster.out
  touch $NEWIT/analysis/CLUST_DONE
  gzip -f $NEWIT/analysis/cluster.out
  touch $NEWIT/analysis/MTX_DONE
endif

